on:
  fork:
  push:
    branches: [staged, master]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>Thanks for submitting an issue!</h1> Welcome to the Heptagram community :nerd_face:'
          pr-message: '<h1>Thanks for your contribution! Someone will review your PR shortly.</h1> Welcome to the community :nerd_face:'
          footer: 'If you would like to continue contributing and would like to talk with other contributors, you should join our <a href="https://discord.gg/HSupF99kpq">Discord Server</a> 
