on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>Thanks for opening an issue! We will triage this shortly.<h1>'
          pr-message: '<h1>Thanks for opening an issue! We will review this PR shortly.<h1>'
          footer: '<h3>Come join our discord server! If you have made a contribution, you can claim a special role there!<h3>'
