name: 'First interaction'
description: 'Greet new contributors when they create their first issue or open their first pull request'
author: 'GitHub'
inputs:
  repo-token:
    description: {{ secrets.GITHUB_TOKEN }}
    required: true
  issue-message:
    description: 'Yay! You have opened your first issue on this repo! Somone will take a look at this issue shortly. In the meantime, you can also join the discord community [here](https://discord.com/invite/HSupF99kpq).'
  pr-message:
    description: 'Yay! You have opened your first PR on this repo! Somone will take a look at this PR shortly. In the meantime, you can also join the discord community [here](https://discord.com/invite/HSupF99kpq).'
runs:
  using: 'docker'
  image: 'Dockerfile'
